```yaml lw-blog-meta
title: 'Gin的错误处理实践'
date: "2020-11-22"
brev: "Golang的优点很多，但是同时也给日志处理带来了挑战。这里结合gin的原生Logger，以及我自己的理解，说说我总结出来的最佳方案。"
tags: ["中间件"]
```

## 背景

我想，如果没有真正经历过互联网生产环境，大概是不会理解到这种需求的存在的。

一个最基本的需求：如何把 "一次客户端请求" 与 "业务代码抛出的异常" 关联起来，便于定位问题？

## 其他语言/框架的实现

首先前端（客户端）应该是没有这种痛苦的。因为用户就一个，好吧就算有并发多个请求，打开控制台都一目了然了，根本用不着多想。

在Python的世界中，有"线程"这个东西。如果不使用异步框架只用传统框架例如 Flask 的话，同一个线程同时只处理一个请求，因此可以把上下文变量直接挂在这个线程上。因此 Flask 这类框架也是没有什么痛苦的。

但是如果我们想搞点事情，开始使用异步框架例如 FastAPI ，问题就出现了：难道我们要将一个（包含 request_id 的）上下文变量 传递到下面所有的业务函数中去吗？这显然是不可能的。

那么，我们如何在打日志的时候，同时打出这个 request_id 呢？

我也不知道。毕竟，我的同事似乎也在为此而烦恼着。

## gin 的错误处理

我们先暂时不管 request_id 这种东西。我们先来看看 gin 框架给我们预置的一套错误处理机制。

故事要从`Logger()`说起。它是 `gin.Default()` 时默认加载的一个中间件。在它的代码中有一行引起了我的注意：

```go
func LoggerWithConfig(conf LoggerConfig) HandlerFunc {
    // ...
    return func(c *Context) {
        // ...
        param.ErrorMessage = c.Errors.ByType(ErrorTypePrivate).String()
        // ...
    }
}
```

也就是说，如果我们向`gin.Context`里面扔了error的话，那么默认的日志中间件会把所有的error都打印出来。

那我们看看这个error长的是什么样子：

```go
// Error represents a error's specification.
type Error struct {
	Err  error
	Type ErrorType
	Meta interface{}
}
```

上面的结构体的意思是，一个包含着底层的原始error，第二个标记着这个所属的类型，第三个可以包含一些额外的参考信息。（其实这套设计与我的想法不谋而合，我的想法在文章后半部分细讲）

首先我们看看我们怎么构造这个`Error`对象。在使用时，我们只需要调用`c.Error(e)`就可以把一个普通的错误丢进去了：

```go
func (c *Context) Error(err error) *Error {
	parsedError, ok := err.(*Error)
	if !ok {
		parsedError = &Error{
			Err:  err,
			Type: ErrorTypePrivate,
		}
	}

	c.Errors = append(c.Errors, parsedError)
	return parsedError
}
```

如果我们投入的是一个其他类型的error，在这个函数中会将其包装成`gin.Error`这个类型，并且标记它的类型为"私有"的。

那么"私有"这个属性会代表着什么呢？——看看前面的代码，它会在`c.Errors.ByType(ErrorTypePrivate)`这里被识别出来并且打印。

那么第三个问题，`meta`这个东西又怎么用呢？我们看一段示例代码及它配套的日志：

```go
func someHandlerFuncWithError(c *gin.Context)  {
	c.Error(errors.New("错误a"))
	c.Error(errors.New("错误b"))
}
```

```text
[GIN] 2020/11/22 - 22:40:06 | 200 |     324.511µs |             ::1 | GET      "/error"
Error #01: 错误a
Error #02: 错误b
```

从上面可以看到，所有投入`gin.Context`中的error，（如果被标记为私有的）会被按照顺序打印出来。

再看看public属性的错误会被如何处理：

```go
func someHandlerFuncWithError(c *gin.Context)  {
	c.Error(errors.New("错误a"))
	c.Error(&gin.Error{
		Err:  errors.New("错误d"),
		Type: gin.ErrorTypePublic,
		Meta: gin.H{"用户名":"lewin","请求的内容":"一些内容"},
	})
	log.Println(c.Errors.ByType(gin.ErrorTypePublic).String())
}
```

```text
2020/11/22 23:21:20 Error #01: 错误d
     Meta: map[用户名:lewin 请求的内容:一些内容]

[GIN] 2020/11/22 - 23:21:20 | 200 |     228.255µs |             ::1 | GET      "/error"
Error #01: 错误a
```

从上面可以看到，非私有的错误不会被Logger()中间件打印出来，如果我们需要的话，可以自己写一个中间件来进行处理。

因此可以得出一个方案，如果我们需要关注 request_id 的话，我们可以考虑将`gin.Context`这个东西到处传递，在每个产生异常的地方直接丢进去。——但是这样也太恶心了吧。

我们也可以考虑用正常的方式，一个error通过函数链一级一级地向上传递，一直到handler函数中再丢进去。——这个的问题在于，我们会丢失掉"案发现场"的信息。

于是，我们需要一种方案，将"案发现场"的信息挂载在error中去，然后通过正常风格的函数返回值，将这个error一步一步地返回到handler函数中去。